export default {
  LOGIN: 'login',
  WEBLINKS: 'Webview',
  OTP_VERIFICATION: 'OtpVerfication',
  OUTER_SCREEN: 'outerScreen',
  SIGN_UP: 'signUp',
  SHORT_CODE: 'shortCode',
  SEND_OTP: 'SendOtp',
  DASHBOARD: 'Dashboard',
  MYPROFILE: 'MyProfile',
  TASKSTACK: 'TaskStack',
  TASKHISTORY: 'TaskHistory',
  PROFILESTACK: 'ProfileStack',
  DRAWER_ROUTES: 'DrawerRoutes',
  TASKDETAIL: 'TaskDetail',
  TASKCANCEL: 'TaskCancel',
  TASKCOMPLETEDOCUMENT: 'TaskCompleteDocument',
  ADDSIGNATURE: 'AddSignature',
  SCANNER: 'Scanner',
  AUTHSTACK: 'AuthStack',
  SETTINGS: 'Settings',
  APPSETTINGSSTACK: 'AppsettingStack',
  WALLET: 'Wallet',
  CONTACTUS: 'ContactUs',
  ORDERDETAIL: 'OrderDetail',
  WALLETSTACK: 'walletStack',
  ADD_MONEY: 'addMoney',
  PAYOUT_STACK: 'payoutStack',
  PAYOUT: 'payout',
  DAMAGEREPORT:"Damagereport",
  REIMBURSEMENT:"Reimbursement",
  CART:"Cart",
  PLACEHOLDERCOMMENTFORPICKUPDRIVER: 'Eg. Please reach before time if possible',
  SEARCHPRODUCTOVENDOR: 'SearchProductVendorItem',
  PRODUCTDETAIL: 'productDetail',
  ORDERCANCEL:"Ordercancel",
  WEBCONNECTIONS:"Webconnections",
  ALL_IN_ONE_PAYMENTS: 'allInOnePayments',
  SUBSCRIPTIONS:'subscriptions',
  SUBSCRIPTION_STACK:'SubscriptionStack',
  CHAT_SCREEN:'ChatScreen',
  CHAT_ROOM:"ChatRoom",

};
